### ISSUE TITLE
Not working in new version's split mode

### ISSUE THREAD

**Issue by sidhant-khamankar** [raphaelheinz/LeetHub-3.0#11]

**Comment by Adrien-LUDWIG** [comment]
Seconded, nothing happens when submitting using the Split View layout.

**Comment by raphaelheinz** [comment]
You are correct. As of now split view is not supported yet. This needs to be implemented.
Currently, it works using the old UI and the new dynamic "flexible" layout.

**Comment by Vivek-C-Shah** [comment]
hey how to get back to the leetcode dynamic layout version from split mode version

**Comment by raphaelheinz** [comment]
There is a button "Dynamic Layout" in the navigation bar on the right side. Please check below image

<img width="434" alt="image" src="https://github.com/raphaelheinz/LeetHub-3.0/assets/28300143/e84d8565-2ea0-4fb2-8b26-18cc464b5bff">

**Comment by Vivek-C-Shah** [comment]
@raphaelheinz idk why it is not visible to me
<img width="921" alt="image" src="https://github.com/raphaelheinz/LeetHub-3.0/assets/94179705/5b551d7a-ce30-4f73-962f-f7dd81aa5199">

**Comment by Vivek-C-Shah** [comment]
checkout @Adrien-LUDWIG @raphaelheinz 
<img width="921" alt="image" src="https://github.com/raphaelheinz/LeetHub-3.0/assets/94179705/8d34d3b7-31ea-4c57-8e5b-01c6c3115478">

am still in the same problem

**Comment by Vivek-C-Shah** [comment]
okay wait, its done one of my browser extension was not letting it show up, now its alright

**Comment by raphaelheinz** [comment]
I am closing this issue because split screen is not supported by Leetcode anymore
