### ISSUE TITLE
Supporting PostgreSQL 

### ISSUE THREAD

**Issue by snowphone** [raphaelheinz/LeetHub-3.0#20]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

It seems uploading PostgreSQL is not supported yet, in contrary of other DBs such as MySQL. So, it would be great if LeetHub v3 will support PostgreSQL.

**Comment by raphaelheinz** [comment]
Hi @snowphone,
Good finding! I have added PostgreSQL to the supported languages in [2c41f29](https://github.com/raphaelheinz/LeetHub-3.0/commit/2c41f29970cf5e42641c33c450e9e4b858e90aa0).
Version v0.0.8 should be available in the store soon :)

**Comment by snowphone** [comment]
Wow... you're so fast! After the release, I'll test it too :)

**Comment by snowphone** [comment]
It works 😀
