### ISSUE TITLE
Leethub v3 not working with the new leetcode UI for me please help!!!

### ISSUE THREAD

**Issue by Vivek-C-Shah** [raphaelheinz/LeetHub-3.0#23]
**Describe the bug**
Leethub v3 not working with the new Leetcode UI

**To Reproduce**
Use the new Leetcode UI not the dynamic one this attached one
<img width="918" alt="image" src="https://github.com/raphaelheinz/LeetHub-3.0/assets/94179705/6287ffdb-8900-4484-9cbc-f5d18045ccfb">

**Comment by raphaelheinz** [comment]
Hi @Vivek-C-Shah,
thanks for reporting this issue. You are right, currently only the "Dynamic Layout" and the old layout is supported. Unfortunately, currently I don't have much time for implementing this feature but its on my backlist.

I am closing this issue as it is also described in #11. Let's move discussion to that thread.
