### ISSUE TITLE
Manual sync button shown in user profile

### ISSUE THREAD

**Issue by raphaelheinz** [raphaelheinz/LeetHub-3.0#26]
**Describe the bug**
Since the last release, a button for manual synchronization has been added. Please check #25 for this. Unfortunately, this button is also shown in the user profile. I am not sure if it is on other pages as well. We will probably need additional checks to make sure this button is only added in an editor page?

**Screenshots**
![image](https://github.com/raphaelheinz/LeetHub-3.0/assets/28300143/fa254f43-900a-490c-8e3f-b44a3458d2b1)

@itsluminous do you have an idea what we can further do?

**Comment by frankbearzou** [comment]
also on problem page.

![image](https://github.com/raphaelheinz/LeetHub-3.0/assets/11401804/6928852e-ab4e-4a22-838a-89862e7ec64f)

**Comment by itsluminous** [comment]
let me add a fix for that

**Comment by raphaelheinz** [comment]
> let me add a fix for that

There is a method ```insertToAnchorElement()``` which checks the URL. Probably the developer of the spinner feature had the same problem when adding

**Comment by itsluminous** [comment]
That code looks too complex for a simple thing I feel.
I have raised a pull request for this issue : #27

**Comment by raphaelheinz** [comment]
This bug has been solved in [989eb0f](https://github.com/raphaelheinz/LeetHub-3.0/pull/27/commits/989eb0fc516b9f5f8ea1f6845daefa7b6ccd1ac0). I created a new release v0.0.11 which is currently being reviewed by Google. Will be in the store soon!
