### ISSUE TITLE
Limit github permissions for Leethub

### ISSUE THREAD

**Issue by krishpy99** [raphaelheinz/LeetHub-3.0#39]
Current behavior:
Leethub requires authorization to read all public and private repositories.

Suggested change:
I want to be able to limit the access of github to public repositories. A more impressive addition to this would be to be able to select which private repositories leethub would have access to.

**Comment by raphaelheinz** [comment]
Hi @krishpy99,
thanks for opening the issue. I agree we should limit the permissions.
However, I am closing this because it is duplicate of #33.
