### ISSUE TITLE
LeetHub -v 3.0 doesn't work for LeetCode new version

### ISSUE THREAD

**Issue by TonyKim9401** [raphaelheinz/LeetHub-3.0#42]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Describe the bug**
I've been using LeetHub 3.0 for the new version of LeetCode. 
It worked with no issues for more than the last six months. I found that about three days ago, even though I submitted and solved problems, the commit wasn't reflected on my GitHub repository.

I changed the LeetCode version from the new to the old and it did work, I didn't touch any settings have no idea why it doesn't work now.

If this only happens to me, that's ok, however if anybody have the same experience I have now, please share your experience.

**To Reproduce**

**Expected behavior**
Work normally.

**Screenshots**
Nan

**Additional context**
Nan

**Comment by TonyKim9401** [comment]
I have no idea why, but it started working properly with the new version.
Sorry to bother you, you can delete this issue if you want.

**Comment by raphaelheinz** [comment]
Hi @TonyKim9401, its good to hear it works again :) I am closing this issue for now. Feel free to reopen if the issue occurs again..
