### ISSUE TITLE
if i make repeated submissions to the same problem, i want to make copy of the files not replace the files with new solutions, i want to have multiple solutions for the same problem

### ISSUE THREAD

**Issue by hacketthadwin** [raphaelheinz/LeetHub-3.0#45]
if i make repeated submissions to the same problem, i want to make copy of the files not replace the files with new solutions, i want to have multiple solutions for the same problem

**Comment by raphaelheinz** [comment]
Hi @hacketthadwin, for that use case you can right-click on the manual push button. Please check the image below. Then you can set a custom suffix and a new file will be created.

<img width="352" alt="image" src="https://github.com/user-attachments/assets/81929a52-5641-47a7-aec0-0262ba8853aa">

Please let me know in case you have further questions. I am closing for now :)
