### ISSUE TITLE
Still does not work on New version of Leetcode UI

### ISSUE THREAD

**Issue by snowphone** [raphaelheinz/LeetHub-3.0#5]
## Please review previous closed issues before filling out a new one! Duplicate issues will be closed without comment.

**Describe the bug**
I tried 0.0.1, 0.0.2, and 0.0.3 but all three versions cannot detect code submissions on newer UI. I'm not a frontend engineer so I can't tell which log is helpful and which one is not. If you specify the prodcedure to collect logs properly, I'll give you ASAP.

**Comment by raphaelheinz** [comment]
Hopefully Leetcode does not continue changing its UI that much in the next future and breaking our plugin on a daily basis...

**Comment by raphaelheinz** [comment]
I merged the pull request and built a new software. Version v0.0.4 should be available in the Web Store soon. Please check then if its working @snowphone .

**Comment by raphaelheinz** [comment]
@snowphone If you are referring to the "easy", "medium" and "hard" counters: They are not synced with your previous submissions. The counters are set to 0 on installation and incremented on every correct problem submission. So it is expected for them to be 0 as in your case.

Does LeetHub v3 create commits in your GitHub repo?

**Comment by raphaelheinz** [comment]
Thanks a lot for your check . Sorry I have not made it clear, I also tested on "Dynamic Layout" so far. Not sure what is the issue with "New Layout" though, we have to check that. 

Good to hear you confirmed it works with "Dynamic Layout" :) I think it is a good basis so we can continue Leetcoding on a modern UI... 🥳

**Comment by viCodexm** [comment]
The extension only functions within a Dynamic Layout.
However, it still does not work in Split Mode.
![image](https://github.com/raphaelheinz/LeetHub-3.0/assets/116115112/313d0edd-6b4e-4778-beb3-f6e59b9d518a)

**Comment by snowphone** [comment]
I think since we're on the same page, it would be better to close this issue and create smaller issues on demand (support "new" layout, split mode, submission shortcut, and so on).
