### ISSUE TITLE
Support detecting submission by keyboard shortcut

### ISSUE THREAD

**Issue by snowphone** [raphaelheinz/LeetHub-3.0#9]
To submit leetcode code, there's two way: 1) Clicking the submit button, 2) Pressing Ctrl + Enter.
The first one works well on dynamic layout, but the latter seems not. And it would be great if submitting by keyboard shortcut is also detected too.

Actually, @arunbhardwaj already tried this before, so it would be a proper point to start.

https://github.com/arunbhardwaj/LeetHub-2.0/pull/31

**Comment by raphaelheinz** [comment]
There were some problems leading to this issue. Wrong textarea listener was subscribed to and the timeout for reading the submission id was too fast. I uploaded v0.0.5 to Chrome Web Store. @snowphone Can you please check?

Unfortunately, I can currently only test on Mac. Found no issue so far with v0.0.5...

**Comment by raphaelheinz** [comment]
@snowphone Did you already have time to check v0.0.5? If you confirm this issue has been fixed, I will close this issue.

**Comment by snowphone** [comment]
I just checked it works really well! As always thanks for your help :)

**Comment by raphaelheinz** [comment]
Okay great, thanks for your confirmation. Good that it works now :)
